name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy-terraform-infra:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./_third_day/8-ci-cd

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./_third_day/8-ci-cd

      - name: Plan Terraform
        run: terraform plan --var-file vars/test.my.tfvars -out=tfplan
        working-directory: ./_third_day/8-ci-cd

      - name: Deploy Terraform
        run: terraform apply --var-file vars/test.my.tfvars --auto-approve tfplan
        working-directory: ./_third_day/8-ci-cd